---
apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapprc
spec:
  replicas: 3
  selector:
    name: javawebapp
  template:
    metadata:
      name: myapp
      labels:
        name: javawebapp
    spec:
      containers:
        - name: myappcontainer
          image: ashokit/javawebapp
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebservice
spec:
  type: NodePort
  selector:
    name: javawebapp 
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
    
...     
       