---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    name: javawebapp
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: httpd
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebservice
spec:
  type: NodePort
  selector:
    name: javawebapp 
  ports:
  - port: 80
    targetport: 8080
    nodePort: 30000
...     
       