---
apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: javawebapprs
spec:
  replicas: 2
  selector:
    matchLabels:
      "app: myapp
      version: v1"
  template:
    metadata:
      name: javawebappcontainer
      labels:
        app: myapp
    spec:
      containers:
      - name: javawebappcontainers
        image: ashokit/javawebapp
        ports:
          - containerPort: 8080            
---
apiVersion: v1
kind: Service
metadata:
  name: javawebservice
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30275  
    