name: Build Java Project
on:
  push:
    branches:
      - 'master'
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install 

      - name: Docker Login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{  secrets.DOCKER_PASSWORD}}  

      - name: Set image tag with timestamp
        id: set_tag
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/myfirstimage:${{github.run_number}}"
          #IMAGE_TAG="snagireddy9/myfirstimage:$(date +'%Y-%m-%d_%H-%M-%S')"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV  
          echo "${{github.run_number}}"

      - name: Build the Docker Image
        run: |
           #IMAGE_TAG="myfirstimage:$(date +'%Y-%m-%d_%H-%M-%S')"
           echo "Building image with tag $IMAGE_TAG"
           docker build . --file Dockerfile --tag $IMAGE_TAG
           #docker build . --file Dockerfile 

      - name: Show the Dokcer images
        run: |
          docker images
       
      - name: Push Docker image to DockerHub
        run: |
           #IMAGE_TAG="myfirstimage" #:$(date +'%Y-%m-%d_%H-%M-%S')"
           docker push $IMAGE_TAG

      #- name: Docker Push
       # run: |
        #  docker tag myfirstimage ${name}/myfirstimage:${{github.run_number}}
         # docker myfirstimage ${name}/myfirstimage:${{github.run_number}}   

      - name: Configure Aws Credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1

      - name: deploy
        run: aws ecs deploy --service my-service --cluster demo1 --task-definition my-task
       











          
