name: Build Java Project
on:
  push:
    branches:
      - 'master'
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install 

      - name: Docker Login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{  secrets.DOCKER_PASSWORD}}  

      - name: Build the Docker Image
        run: |
           IMAGE_TAG="myfirstimage:$(date +'%Y-%m-%d_%H-%M-%S')"
           echo "Building image with tag $IMAGE_TAG"
           docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Show the Dokcer images
        run: |
          docker images
       
      - name: Push Docker image to DockerHub
        run: |
           IMAGE_TAG="myfirstimage" #:$(date +'%Y-%m-%d_%H-%M-%S')"
           docker push $IMAGE_TAG
           











          
